# Generated by Django 5.0.6 on 2024-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0004_alter_kelompokbarang_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompokbarang',
            name='prefix',
            field=models.CharField(default=None, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
