# Generated by Django 5.0.6 on 2024-05-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0006_alter_satuanbarang_kode_barang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KelompokBarang',
            new_name='Barang',
        ),
    ]
